project:
  type: website
  output-dir: docs

website:
  title: "[ANDREW JOHN DICKINSON]{.title}"
  open-graph:
    locale: es_ES
    site-name: ajdickinson
  # site-url: "https://www.quarto.org"
  # favicon: images/forest.svg
  favicon: images/favicon.svg
  search: false
  navbar:
    background: light
    left:
      - href: index.qmd
        text: "main"
      - href: research.qmd
      - href: teaching.qmd
      - href: contact.qmd
      - href: vita.qmd
    # tools:
    right:
      - icon: github
        href: https://github.com/ajdickinson
      - icon: linkedin
        href: https://www.linkedin.com/in/andrew-dickinson-675266253/

  # back-to-top-navigation: true
  page-footer: 
      background: light
      center: 
        - "© Copyright 2025, Andrew John Dickinson"

format:
  html: 
    # page-layout: custom
    grid:
      sidebar-width: 35px
      body-width: 1800px
      margin-width: 500px
      gutter-width: 3.5rem
    theme: 
      - styles.scss
    toc: true
    mainfont: Fira Sans Extra Condensed
    monofont: JetBrains Mono
    text-align: 'left'
   