---
title: "research"
toc: false
---


### [published]{.mono .l}

---

[**Productivity losses in the transition to Daylight Saving Time: Evidence from hourly GitHub activity**](https://doi.org/10.1016/j.jebo.2024.106749)  

[Andrew Dickinson](ajdickinson.github.io) and [Glen R. Waddell](https://www.glenwaddell.com/). 2024. _Journal of Economic Behavior & Organization_.

_Abstract:_  

> Using data on GitHub users around the world, we estimate the effects of transitions to Day-light Saving Time on worker activity. In daily activity, transitions appear short lived—there is evidence of two days of declines before activity returns to baseline levels. However, hourly analysis reveals a transition to Daylight Saving Time that is much longer—losses appear in the early working hours of work days into a second week following the initiation of Daylight Saving Time.

<br>
<br>

[**The Effect of E-Verify Laws on Crime**](https://doi.org/10.1177/00197939211044449)

[Brandon Churchill](https://brandynchurchill.com/), [Andrew Dickinson](ajdickinson.github.io), [Taylor Mackay](https://tmackay.io/), and [Joseph J. Sabia](https://economics.sdsu.edu/faculty/sabia). 2022. _Industrial and Labor Relations Review_, 75(5).

_Abstract:_  

> E-Verify laws, which have been adopted by 23 states, require employers to verify whether new employees are eligible to legally work prior to employment. This study explores the impact of state E-Verify laws on crime. Using data from the 2004–2015 National Incident Based Reporting System, the authors find that the enactment of E-Verify is associated with a 7% reduction in property crime incidents involving Hispanic arrestees. This finding was strongest for universal E-Verify mandates that extend to private employers and its external validity bolstered by evidence from the Uniform Crime Reports. Supplemental analyses from the Current Population Survey suggest two mechanisms to explain this result: E-Verify-induced increases in the employment of low-skilled natives of Hispanic descent and out-migration of younger Hispanics. Findings show no evidence that arrests were displaced to nearby jurisdictions without E-Verify or that violent crime or arrests of African Americans were affected by E-Verify laws. The magnitudes of the estimates suggest that E-Verify laws averted $491 million in property crime costs to the United States.


### [in progress]{.mono .l}

---

**Environmental prediction for diverse contexts**: Insights for contemporary PM2.5 research and policy  

[Andrew Dickinson](ajdickinson.github.io) and [Ed Rubin](edrub.in)

_Abstract:_  

> Recent advances in remote sensing, computational hardware, and machine learning/AI have enabled the prediction of environmental features like PM~2.5~ at high spatial and temporal resolutions. While such predictions significantly expand the coverage of pollution measurement, their accuracy and reliability depend crucially on methodological choices—considerations easily overlooked by downstream consumers of these predictions. We examine these methodological choices in the context of PM~2.5~ prediction across the contiguous United States from 2002–2019. Our analysis investigates how the modeling and validation decisions underlying these data affect (1) predictions' perceived accuracy for different tasks, (2) predictions' suitability throughout space, and (3) results in downstream empirical analyses. First, we evaluate model performance across conventional independent and spatially explicit cross-validation strategies, demonstrating that standard validation methods substantially overstate predictive accuracy due to data leakage. We propose a novel monitor-presence probability model to subset predicted PM~2.5~ to areas most similar to the training data, providing a more reliable set of estimates for empirical analyses. Finally, we illustrate how modeling the relationship between predicted PM~2.5~ and demographic characteristics alter empirical conclusions. Our results emphasize the importance of matching validation and uncertainty quantification to downstream empirical use.

_Slides_: [TWEEDS 2025](./files/dickinson-tweeds25.pdf) [(download)]{.mono .l .small}
