---
title: "cv"
---

[`pdf download `](vita/dickinson-cv.pdf)

## Education

Ph.D., Economics, University of Oregon (expected 2025)  
M.S., Economics, University of Oregon (2021)  
M.A., Economics, San Diego State University (2019)  
B.A., Economics, San Diego State University (2017)  

## Research Fields

__Primary:__ Environmental Economics, Applied Econometrics, Labor Economics  
__Secondary:__ Health Economics, Crime, Development Economics  
__Expertise__: Data Science, Causal Inference, ML, Geospatial Analysis, Data Visualization  

## Publications

- "Productivity losses in the transition to Daylight Saving Time: Evidence from hourly GitHub activity." (2024). **Journal of Economic Behavior & Organization**. With [Glen R. Waddell](https://glenwaddell.com). [DOI: 10.1016/j.jebo.2024.106749](https://doi.org/10.1016/j.jebo.2024.106749)  
- "The Effect of E-Verify Laws on Crime." (2021). **Industrial Labor Relations Review**. With [Brandyn F. Churchill](https://brandynchurchill.com/), [Taylor Mackay](https://tmackay.io/), & [Joseph J. Sabia](https://economics.sdsu.edu/faculty/sabia). [DOI: 10.1177/00197939211044449](https://doi.org/10.1177/00197939211044449)

## Works in Progress

- "Environmental prediction for diverse contexts: Insights for contemporary PM2.5 research and policy." With [Ed Rubin](https://edrub.in).  
- "Impact of Credit Linkages Among Ugandan Savings Groups." With [Alfredo Burlando](https://www.alfredoburlando.com/), [Jessica Goldberg](https://econweb.umd.edu/~goldberg/index.html), & [Luciana Etcheverry](https://blogs.iadb.org/igualdad/en/author/lucianaetcheverry/)

<!-- ## Other Research
- "Have U.S. Gun Buyback Programs Misfired?". D. M. Anderson, T. Ferrazares, & J. Sabia. (2020). **National Bureau of Economic Research**, (No. w28763).
- "Did the War on Terror Ignite an Opioid Epidemic?". R. Cesur, J. Sabia, & W. Bradford, (2019). **National Bureau of Economic Research**, (No. w26264).
- "War! What is it Good For? The Effects of Combat Service on Economic Transitions of Veterans." J. Sabia & W. Skimmyhorn, (2018). **Economic Self-Sufficiency Policy Research Institute**, (No. 20181). -->


## Experience

**Research Assistant** | Prof. Alfredo Burlando | *University of Oregon*  | _2023-2024_  
**Research Fellow** | Center for Health Economics and Policy Studies at San Diego State University | _2017-2019_  

## Teaching

**Instructor** | *University of Oregon*  

- **EC 320**: Introduction to Econometrics I: [Spring 2023](https://github.com/ajdickinson/EC320S23), [Spring 2024](https://github.com/ajdickinson/EC320S24) (Undergraduate)
- **EC 330**: Urban and Regional Economic Problems: Summer 2021, Fall 2021, Fall 2022 (Undergraduate)

**Teaching Assistant** | *University of Oregon*  

- EC 490/590 -- Development Economics: Winter 2025 (Master's)  
- EC 425/525 -- Econometrics: Spring 2021 (Master's)  
- EC 424/524 -- Econometrics (Machine Learning and Prediction): [Winter 2022](https://github.com/edrubin/EC524W22), [Winter 2025](https://github.com/edrubin/EC524W25) (Master's)  
- EC 421 -- Introduction to Econometrics II: Fall 2020, Spring 2021, [Fall 2023](https://github.com/ajdickinson/EC421F23_lab), Fall 2024 (Undergraduate)  
- EC 320 -- Introduction to Econometrics I: Winter 2024, Spring 2025 (Undergraduate)  
- EC 330 -- Urban and Regional Economic Problems: Spring 2022 (Undergraduate)  
- EC 311 -- Intermediate Microeconomic Theory: Spring 2021: Spring 2020 (Undergraduate)  
- EC 202 -- Introduction to Economic Analysis: Macroeconomics: Winter 2020 (Undergraduate)  
- EC 201 -- Introduction to Economic Analysis: Microeconomics: Winter 2021, Winter 2022 (Undergraduate)  
- EC 101 -- Contemporary Economic Issues: Fall 2019 (Undergraduate)  

## Awards
- Kleinsorge Fellowship (2023)
- Core Exam Completion Award (2020)
- Graduate Teaching Fellowship (2019 - present)
- McCuen Endowed Economics Scholarship (2017, 2018)
- Center for Public Economics Paper Award (2018)

## Activities

- TWEEDS _2025_, Western Economic Association International Conference _2019_, Association for Public Policy and Management _2018_ (poster session)
<!-- - Attendee at Eastern Economics Association conference _2018_, Economic Self-Sufficiency Policy Research Institute Workshop _2017_ -->
<!-- - Editor for Undergraduate Research Journal of the College of Arts and Letters _2016_ -->

## Professional Service

- Referee for *Economic Inquiry* (2022)

## Software

__Computing__: R, SQL (BigQuery, DuckDB), Python, QGIS, Stata, SAS  
__Workflow__: Bash/Unix, Git, Docker  
__Cloud__: Google Cloud Platform, AWS, Spark  
__Design__: Markdown, Quarto, $\LaTeX$, typst, CSS, Shiny  

## References

:::: {.columns}

::: {.column width="50%"}

__Ed Rubin__  (Co-Chair)  
Assistant Professor  
Department of Economics  
University of Oregon  
[edrub.in](https://edrub.in)

__Grant McDermott__  
Principal Economist  
Amazon  
[grantmcdermott.com](https://grantmcdermott.com/)

:::

::: {.column width="50%"}
__Glen R. Waddell__  (Co-Chair)  
Professor  
Department of Economics  
University of Oregon  
IZA Research Fellow  
[glenwaddell.com](https://glenwaddell.com)

:::

::::


## Contact
**Address:**  
Department of Economics  
Prince Lucian Campbell Hall  
1285 University of Oregon  
Eugene, OR 97403-1285  

**Email:** adickin3 at uoregon period edu  
**Github:** ajdickinson  